[2024-02-27T15:49:31.385+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: classic_python_operator.print_execution_date scheduled__2024-02-26T03:00:00+00:00 [queued]>
[2024-02-27T15:49:31.391+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: classic_python_operator.print_execution_date scheduled__2024-02-26T03:00:00+00:00 [queued]>
[2024-02-27T15:49:31.392+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-02-27T15:49:31.400+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): print_execution_date> on 2024-02-26 03:00:00+00:00
[2024-02-27T15:49:31.403+0000] {standard_task_runner.py:60} INFO - Started process 425 to run task
[2024-02-27T15:49:31.405+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'classic_python_operator', 'print_execution_date', 'scheduled__2024-02-26T03:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/classic_python_operator.py', '--cfg-path', '/tmp/tmp9489gd35']
[2024-02-27T15:49:31.406+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask print_execution_date
[2024-02-27T15:49:31.460+0000] {task_command.py:423} INFO - Running <TaskInstance: classic_python_operator.print_execution_date scheduled__2024-02-26T03:00:00+00:00 [running]> on host 1927bc465fbc
[2024-02-27T15:49:31.557+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vutt' AIRFLOW_CTX_DAG_ID='classic_python_operator' AIRFLOW_CTX_TASK_ID='print_execution_date' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T03:00:00+00:00'
[2024-02-27T15:49:31.558+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/classic_python_operator.py", line 6, in _print_execution_date
    execution_date = kwargs['print_execution_date']
                     ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'print_execution_date'
[2024-02-27T15:49:31.575+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=classic_python_operator, task_id=print_execution_date, execution_date=20240226T030000, start_date=20240227T154931, end_date=20240227T154931
[2024-02-27T15:49:31.589+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task print_execution_date ('print_execution_date'; 425)
[2024-02-27T15:49:31.617+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-27T15:49:31.662+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-27T15:50:25.531+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: classic_python_operator.print_execution_date scheduled__2024-02-26T03:00:00+00:00 [queued]>
[2024-02-27T15:50:25.536+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: classic_python_operator.print_execution_date scheduled__2024-02-26T03:00:00+00:00 [queued]>
[2024-02-27T15:50:25.537+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-02-27T15:50:25.546+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): print_execution_date> on 2024-02-26 03:00:00+00:00
[2024-02-27T15:50:25.550+0000] {standard_task_runner.py:60} INFO - Started process 441 to run task
[2024-02-27T15:50:25.551+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'classic_python_operator', 'print_execution_date', 'scheduled__2024-02-26T03:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/classic_python_operator.py', '--cfg-path', '/tmp/tmpcde6mpjq']
[2024-02-27T15:50:25.553+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask print_execution_date
[2024-02-27T15:50:25.611+0000] {task_command.py:423} INFO - Running <TaskInstance: classic_python_operator.print_execution_date scheduled__2024-02-26T03:00:00+00:00 [running]> on host 1927bc465fbc
[2024-02-27T15:50:25.706+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vutt' AIRFLOW_CTX_DAG_ID='classic_python_operator' AIRFLOW_CTX_TASK_ID='print_execution_date' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-26T03:00:00+00:00'
[2024-02-27T15:50:25.707+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/utils/context.py:315: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2024-02-27T15:50:25.707+0000] {logging_mixin.py:188} INFO - 2024-02-26 03:00:00+00:00
[2024-02-27T15:50:25.708+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-02-27T15:50:25.721+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=classic_python_operator, task_id=print_execution_date, execution_date=20240226T030000, start_date=20240227T155025, end_date=20240227T155025
[2024-02-27T15:50:25.765+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-27T15:50:25.793+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
